# Generated by Django 5.2.6 on 2025-09-25 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='color',
            field=models.CharField(default='orange', max_length=20),
        ),
        migrations.AddField(
            model_name='appointment',
            name='done',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='appointment',
            name='priority',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Niedrig'), (2, 'Normal'), (3, 'Wichtig')], default=2),
        ),
    ]
