# Generated by Django 5.2.6 on 2025-09-26 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_appointment_color_remove_appointment_done_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='color',
            field=models.CharField(default='orange', max_length=20),
        ),
        migrations.AddField(
            model_name='appointment',
            name='done',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='appointment',
            name='priority',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Niedrig'), (2, 'Normal'), (3, 'Wichtig')], default=2),
        ),
    ]
