# Generated by Django 5.2.6 on 2025-09-26 19:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_appointment_color_appointment_done_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='color',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='done',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='priority',
        ),
    ]
