# Generated by Django 5.2.6 on 2025-09-26 20:08

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_remove_appointment_color_remove_appointment_done_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='category',
            field=models.CharField(choices=[('orange', 'Haushalt'), ('blue', 'Ordnung'), ('green', 'Gesundheit'), ('red', 'Studium'), ('purple', 'Sonstiges')], default='orange', max_length=20),
        ),
        migrations.AddField(
            model_name='appointment',
            name='done',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='appointment',
            name='priority',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Niedrig'), (2, 'Normal'), (3, 'Wichtig')], default=2),
        ),
        migrations.AddIndex(
            model_name='appointment',
            index=models.Index(fields=['user', 'start'], name='api_appoint_user_id_21ebbe_idx'),
        ),
        migrations.AddIndex(
            model_name='appointment',
            index=models.Index(fields=['user', 'category'], name='api_appoint_user_id_e03f3e_idx'),
        ),
        migrations.AddIndex(
            model_name='appointment',
            index=models.Index(fields=['user', 'priority'], name='api_appoint_user_id_5777a2_idx'),
        ),
        migrations.AddIndex(
            model_name='appointment',
            index=models.Index(fields=['user', 'done'], name='api_appoint_user_id_1c9ac9_idx'),
        ),
    ]
